language: java
jdk:
  - openjdk7

before_install:
  - wget http://dl.google.com/android/android-sdk_r22-linux.tgz
  - tar -zxf android-sdk_r22-linux.tgz
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  - android list sdk
  - echo "y" | android update sdk --filter platform-tools,build-tools,android-17 --no-ui --force

script:
  - ls -l
  - pwd
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
  - cd TravisTest
  - ./gradlew assemble
