language: java
jdk:
  - openjdk7

before_install:
  - wget http://dl.google.com/android/android-sdk_r22-linux.tgz
  - tar -zxf android-sdk_r22-linux.tgz
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  - echo "y" | android update sdk --filter platform-tools,build-tools,android-17 --no-ui --force
  - wget https://dl-ssl.google.com/android/repository/build-tools_r17-linux.zip
  - unzip build-tools_r17-linux.zip
  - mv android-4.2.2 $ANDROID_HOME/build-tools/17.0.0
  - ls -l $ANDROID_HOME
  - ls -l $ANDROID_HOME/build-tools
  - ls -l $ANDROID_HOME/build-tools/17.0.0

script:
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
  - cd TravisTest
  - ./gradlew assemble
