language: java
jdk:
  - openjdk7

before_install:
  - wget https://dl.dropboxusercontent.com/u/2202216/android-sdk-linux.zip
  - unzip android-sdk-linux.zip

script:
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
  - cd TravisTest
  - ./gradlew assemble
